version: '3'
services:
  mongo-node1:
    container_name: mongo-node1
    image: mongo:$MongoVer
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "../keyFile.file:/keyfile.tmp"
      - "./conf/:$ConfPath/"
      - "./cmd/:$CmdPath/"
      - "./script/:$ScriptPath/"
      - "./store/data/mongo1:$StorePath/data/"
      - "./store/logs/mongo1/:$StorePath/logs/"    
      - "./.env:/.env" 
    ports:
      - "30017:27017"
    restart: always
    command: "bash $CmdPath/bootstrap.sh"